apiVersion: v1
kind: Service
metadata:
  name: api-2-service
  namespace: default
spec:
  selector:
    app: api-2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-2-depl
  namespace: default
  labels:
    app: api-2
spec:
  selector:
    matchLabels:
      app: api-2
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-2
    spec:
      containers:
        - name: api-2
          image: bobput/back-end-2:latest
          env:
            - name: MY_ENV_VARIABLE
              valueFrom:
                configMapKeyRef:
                  name: back-end-2-configmap
                  key: MY_ENV_VARIABLE
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: back-end-2-configmap
data:
  # Add your key-value pairs here
  MY_ENV_VARIABLE: {{.Values.envValue}}
